import { Box } from '@mui/material';
import Head from 'next/head';
import { NavBar } from '../ui';
import { Footer } from '../ui';
import Link from 'next/link';
interface LayoutProps {
    children: React.ReactNode;
}

export const Layout = ({children}:LayoutProps) => {
  return (
    <div className="contenedor-app">
        <Head>
        <title>Waves App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Link rel="icon" href="/favicon.ico" />
        <Link rel="preconnect" href="https://fonts.googleapis.com"/>
        <Link rel="preconnect" href="https://fonts.gstatic.com" />
        <Link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap" rel="stylesheet"/>
        <Link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" />
      </Head>
      <NavBar/>

      <Box>
    {children}
      </Box>
      <Footer/> 
    </div>
  )
}
