import { Box } from '@mui/material';
import Head from 'next/head';
import { NavBar } from '../ui';
import { Footer } from '../ui';

interface LayoutProps {
    children: React.ReactNode;
}

export const Layout = ({children}:LayoutProps) => {
  return (
    <>
        <Head>
        <title>Cafecito App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap" rel="stylesheet"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" />
      </Head>
      <NavBar/>

      <Box sx={{
      padding:'10px 20px',
      margin:'40px 0px',
  }}>
    {children}
      </Box>
      <Footer/> 
    </>
  )
}
